framework:
    messenger:
        transports:
            product_sync:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: products
                        type: fanout
                    queues: []
            order_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: orders
                        type: fanout
                    queues:
                        product_service_order_placed: ~

        routing:
            Shared\Message\ProductSyncMessage: product_sync
