
services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/amqp-messenger ###
  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"
###< symfony/amqp-messenger ###
